package bdbeans;
// Generated 3 oct. 2023, 00:46:00 by Hibernate Tools 5.6.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur implements java.io.Serializable {

	private int idUtilisateur;
	private String prenom;
	private String nom;
	private String email;
	private String phone;
	private String password;
	private Set rendezvouses = new HashSet(0);

	public Utilisateur() {
	}

	public Utilisateur(int idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	public Utilisateur(int idUtilisateur, String prenom, String nom, String email, String phone, String password,
			Set rendezvouses) {
		this.idUtilisateur = idUtilisateur;
		this.prenom = prenom;
		this.nom = nom;
		this.email = email;
		this.phone = phone;
		this.password = password;
		this.rendezvouses = rendezvouses;
	}

	public int getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(int idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getRendezvouses() {
		return this.rendezvouses;
	}

	public void setRendezvouses(Set rendezvouses) {
		this.rendezvouses = rendezvouses;
	}

}
